name: Texas Covid Vaccinations County Level data

on:
  schedule:
  #   Run wednesday, at 7 pm EDT (UTC -6).
    - cron: 0 23 * * 3


jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set current datetime for file capture
      run: echo "CURR_TIME=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

    -name: Set current date for remote xl file name
      run; echo "CURR_DATE=$(date + '%Y%m%d') >> $GITHUB_ENV

    - name: Set base file name
      run: echo "BASE_FILE_NAME=texas_county_level_vaccinations" >> $GITHUB_ENV

    - name: Fetch fresh file
      run: |
        curl https://www.dshs.texas.gov/sites/default/files/LIDS-Immunize-COVID19/COVID%20Dashboard/County%20Dashboard/COVID-19%20Vaccine%20Data%20by%20County_${{ env.CURR_DATE }}.xlsx -o "${{ env.BASE_FILE_NAME }}.xlsx"
        mv "${{ env.BASE_FILE_NAME }}.xlsx" "texas_vaccinations/${{ env.BASE_FILE_NAME }}-${{ env.CURR_TIME }}.xlsx"

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4.9.2
      with:
        commit_message: Updating texas_vaccination_data
        file_pattern: .
        commit_author: Patrick Farrell <mr.patfarrell@gmail.com>
