name: Texas Covid Vaccinations County Level data

on:
  schedule:
  #   Run every day, at 6 pm.
    - cron:  '0,15,30,45 * * * *'


jobs:
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set current date
      run: echo "CURR_TIME=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

    - name: Set base file name
      run: echo "BASE_FILE_NAME=texas_county_level_vaccinations" >> $GITHUB_ENV

    - name: Fetch fresh file
      run: |
        curl https://dshs.texas.gov/immunize/covid19/COVID-19-Vaccine-Data-by-County.xls -o "${{ env.BASE_FILE_NAME }}.xlsx"
        mv "${{ env.BASE_FILE_NAME }}.xlsx" "texas_vaccinations/${{ env.BASE_FILE_NAME }}-${{ env.CURR_TIME }}.xlsx

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4.9.2
      with:
        commit_message: Updating texas_vaccination_data
        file_pattern: texas_vacccinations/*
        commit_author: GitHub Actions <actions@github.com>
